/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentDevToolsRouteImport } from './routes/agent/dev-tools'
import { Route as AgentKnowledgeRouteImport } from './routes/agent/knowledge'
import { Route as AgentPlaygroundRouteImport } from './routes/agent/playground'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDevToolsRoute = AgentDevToolsRouteImport.update({
  id: '/agent/dev-tools',
  path: '/agent/dev-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentKnowledgeRoute = AgentKnowledgeRouteImport.update({
  id: '/agent/knowledge',
  path: '/agent/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPlaygroundRoute = AgentPlaygroundRouteImport.update({
  id: '/agent/playground',
  path: '/agent/playground',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent/dev-tools': typeof AgentDevToolsRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/playground': typeof AgentPlaygroundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent/dev-tools': typeof AgentDevToolsRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/playground': typeof AgentPlaygroundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent/dev-tools': typeof AgentDevToolsRoute
  '/agent/knowledge': typeof AgentKnowledgeRoute
  '/agent/playground': typeof AgentPlaygroundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent/dev-tools' | '/agent/knowledge' | '/agent/playground'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent/dev-tools' | '/agent/knowledge' | '/agent/playground'
  id:
    | '__root__'
    | '/'
    | '/agent/dev-tools'
    | '/agent/knowledge'
    | '/agent/playground'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDevToolsRoute: typeof AgentDevToolsRoute
  AgentKnowledgeRoute: typeof AgentKnowledgeRoute
  AgentPlaygroundRoute: typeof AgentPlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/dev-tools': {
      id: '/agent/dev-tools'
      path: '/agent/dev-tools'
      fullPath: '/agent/dev-tools'
      preLoaderRoute: typeof AgentDevToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/knowledge': {
      id: '/agent/knowledge'
      path: '/agent/knowledge'
      fullPath: '/agent/knowledge'
      preLoaderRoute: typeof AgentKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/playground': {
      id: '/agent/playground'
      path: '/agent/playground'
      fullPath: '/agent/playground'
      preLoaderRoute: typeof AgentPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDevToolsRoute: AgentDevToolsRoute,
  AgentKnowledgeRoute: AgentKnowledgeRoute,
  AgentPlaygroundRoute: AgentPlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
